# 数据库驱动
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库URL
    url: jdbc:mysql://114.67.125.141:3306/Baixw?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# 日志输出格式
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%X{traceId}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"




